//
// transaction.rs
// Copyright (C) 2023 db3.network Author imotai <codego.me@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

use rs_merkle::{algorithms::Sha256, Error, Hasher, MerkleTree};

//
// the doc of ar transaction can be found from https://docs.arweave.org/developers/server/http-api#transaction-format
//
//
pub struct ArTransaction<'a> {
    // the data format version 1 or 2, 2 is the newest version
    format: i32,
    // the transaction id generated by sha-256 hash of transaction signature
    id: &'a str,
    // use the /tx_anchor to get the last tx
    last_tx: &'a str,
    // RSA public key
    owner: &'a str,
    // the value should be a base64 string
    tags: Vec<(String, String)>,
    // the target address generated by sha-256 hash of RSA public key
    target: &'a str,
    // the amount to transfer from owner to the target
    quantity: &'a str,
    // the merkle root of the transaction data and a base64 string
    data_root: &'a str,
    // a integer string 
    data_size: &'a str,
    // deprecated in v2 data format
    data: &'a str,
    // a reward in winston string
    reward: &'a str,
    // the signature in base64 format
    signature: &'a str,
}


impl<'a> ArTransaction<'a> {
    pub fn gen_root(&self)-> Vec<u8> {
        let fields:Vec<Vec<u8>> = Vec::new();
    }
}


#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {}
}
